### ISSUE TITLE
[BUG] It is no longer possible to drag spaces to reorder them

### ISSUE THREAD

**Issue by garbi** [yuanzhoucq/Tab-Space#101]
Since Safari 16.4, dragging spaces to reorder them in the list of tab spaces is no longer possible.

1. Go to the list of tab spaces and click on the four horizontal lines next to the title of a tab space
2. Try to drag that tab space to change its position in the list of tab spaces
4. Instead of drag-and-drop, this action selects the text next to the four horizontal lines

 - macOS 13.3.1
 - Safari 16.4
 - TabSpace 3.8.4

**Comment by yuanzhoucq** [comment]
Thanks for reporting. We will look into it!

**Comment by garbi** [comment]
Here goes a short video showing the behavior I have on my computer:

https://user-images.githubusercontent.com/982774/230932645-d705a617-aa53-498f-a2c1-929523c746a1.mov

BTW, I really enjoy using TabSpace!

**Comment by gingerbeardman** [comment]
16.4 has some big changes in CSS support, it broke another extension I use which had some arguably invalid CSS that had not shown any problems for 6 years, and then 16.4 makes things a bit more strict and it broke. So that is what I would check first.

Not sure how you can check 16.3, maybe with an old version of Safari Technology Preview or WebKit?

**Comment by yuanzhoucq** [comment]
A new version that addresses this issue has been uploaded to the App Store. Give it a try 😄.

**Comment by garbi** [comment]
It works now. Thanks!
