### ISSUE TITLE
OneTab Imports fails to import multiple sessions

### ISSUE THREAD

**Issue by dfinley** [yuanzhoucq/Tab-Space#18]
When importing from the OneTab Chrome extension, TabSpace is able to import one group of sessions just fine.  When there are multiple groups, the import doesn't process.

The expected behavior would be to import multiple groups of sessions at once.

MacOS 10.15.4
Safari 13.1
Tab-Space 3.6.1

**Comment by yuanzhoucq** [comment]
Hi @dfinley, it works for me when importing multiple groups. Since there is no documentation for OneTab's text format. I only observe it from my a few sessions. Maybe they are not representative enough. Could you please share your failed importing session after deleting sensitive tabs? (joyuercn@icloud.com) I will try to identify the issue and fix it, thank you!

**Comment by yuanzhoucq** [comment]
Fixed in version 3.6.3
