### ISSUE TITLE
Tab Space does not work unless it's allowed to phone home to http://joyuer.cn

### ISSUE THREAD

**Issue by n3bulous** [yuanzhoucq/Tab-Space#23]
Just a minor concern.  I'm assuming it's for tracking installs?

**Comment by yuanzhoucq** [comment]
No, it’s not for tracking. It’s a trick. It is very strange that the extension web page of Safari could not talk to the extension itself because this page is loaded with the scheme “safari-extension”. Only “http” web page could talk to Safari extension. So I embedded an [empty page](http://tabspacestatic.joyuer.cn) as a bridge. It’s only for helping communicate with Tab Space extension. 😅
